apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-logging-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-prod

  source:
    repoURL: https://github.com/So1S/deploy.git
    targetRevision: SO1S-374-deploy-alb-적용을-위한-service-수정
    path: charts/logging

    helm:
      releaseName: logging
      valueFiles:
        - prod-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
