vender: "AWS" # AWS | on-premise

environment: "develop"

fullnameOverride: "so1s-dev"

image:
  repository: "ghcr.io/so1s/api-server"
  tag: "latest"

imagePullSecrets:
  - name: so1s

imagePullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

tolerations:
  - key: kind
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"

resourceQuota:
  cpu: "2000m"
  memory: 2500Mi

resources:
  limits:
    memory: "450Mi"
    cpu: "300m"
  requests:
    memory: "450Mi"
    cpu: "300m"

ingress:
  enabled: false

service:
  type: "ClusterIP"

swagger:
  image:
    repository: swaggerapi/swagger-ui
    tag: v4.13.2

  imagePullSecrets:
    - name: so1s

  imagePullPolicy: Always

  resources:
    limits:
      memory: "50Mi"
      cpu: "25m"
    requests:
      memory: "50Mi"
      cpu: "25m"


  tolerations:
    - key: kind
      operator: "Equal"
      value: "api"
      effect: "NoSchedule"


  ingress:
    enabled: false
  
  service:
    type: "ClusterIP"
    port: 80
    targetPort: 8080