vender: "AWS" # AWS | on-premise

environment: "develop"

fullnameOverride: "so1s-dev" # 중복된 ClusterRole이 생기면 안되므로 각자 이름을 써놓고 작업해주세요

istioInject:
    enabled: true

gpuScheduler:
  enabled: true

image:
  repository: "ghcr.io/so1s/api-server"
  tag: "latest"

imagePullSecrets:
  - name: so1s

imagePullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

resourceQuota:
  cpu: "2000m"
  memory: 2500Mi

resources:
  limits:
    memory: "450Mi"
    cpu: "300m"
  requests:
    memory: "450Mi"
    cpu: "300m"

ingress:
  annotations: {}
  hosts:
    - test-backend.so1s.io
  paths:
    - /
  tls: []

serviceMonitor:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  namespace: backend
  interval: 30s
  telemetryPath: /actuator/prometheus
  labels:
    release: monitoring
  timeout: 10s

swagger:
  istioInject:
    enabled: true

  image:
    repository: swaggerapi/swagger-ui
    tag: v4.13.2

  imagePullSecrets:
    - name: so1s

  imagePullPolicy: Always

  resources:
    limits:
      memory: "50Mi"
      cpu: "25m"
    requests:
      memory: "50Mi"
      cpu: "25m"

  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - test-swagger.so1s.io
    paths:
      - /
    tls: []

  service:
    port: 80
    targetPort: 8080

preInstall:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"