vender: "AWS" # AWS | on-premise

environment: "production"

fullnameOverride: "so1s-prod" # 중복된 ClusterRole이 생기면 안되므로 각자 이름을 써놓고 작업해주세요

image:
  repository: "ghcr.io/so1s/api-server"
  tag: "0.3.0" #반드시 변경

imagePullSecrets:
  - name: so1s

imagePullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

tolerations:
  - key: kind
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"

resourceQuota:
  cpu: "4000m"
  memory: 5Gi

resources:
  limits:
    memory: "900Mi"
    cpu: "600m"
  requests:
    memory: "900Mi"
    cpu: "600m"

ingress:
  annotations:
    kubernetes.io/ingress.class: alb #alb를 사용한다는 의미
    alb.ingress.kubernetes.io/target-type: instance #target이 ec2 인스턴스
    alb.ingress.kubernetes.io/scheme: internet-facing #외부에 노출
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-port: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:089143290485:certificate/8f20bc85-876b-47a2-8c9f-27e9f5455ca9"
    external-dns.alpha.kubernetes.io/hostname: www.so1s.io
  hosts: 
    - www.so1s.io
  paths:
    - /
  tls: []

swagger:
  resources:
    limits:
      memory: "100Mi"
      cpu: "50m"
    requests:
      memory: "50Mi"
      cpu: "30m"
  tolerations:
    - key: kind
      operator: "Equal"
      value: "api"
      effect: "NoSchedule"
  
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-port: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:089143290485:certificate/8f20bc85-876b-47a2-8c9f-27e9f5455ca9"
      external-dns.alpha.kubernetes.io/hostname: swagger.so1s.io
    hosts: 
      - swagger.so1s.io
    paths:
      - /
    tls: []