
vender: "AWS" # AWS | on-premise

environment: "develop" # develop | production

namespaceOverride: ""

replicaCount: 1

hostname: ""

image:
  name: ""
  repository: ""
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

imagePullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
  labels: {}
  hosts: []
  paths: []
  tls: []
  pathType: ""
  servicePort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

resourceQuota: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

swagger:
  image:
    repository: swaggerapi/swagger-ui
    tag: v4.13.2
  imagePullSecrets: []
  imagePullPolicy: Always

  replicaCount: 1

  istioInject:
    enabled: true

  resources: {}
  tolerations: []
  
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    hosts: []
    paths: []
    tls: []
    pathType: ""
    servicePort: 80

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

pullSecret:
  enabled: false
  dockerConfigJson: ""